spring:
  application:
    name: authorization-server

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:80


server:
  port: 80

logging:
  level:
    org.springframework.security: trace

